### ISSUE TITLE
[ENHANCEMENT] Reverse geocoding language problem

### ISSUE THREAD

**Issue by aczone** [kvangent/PokeAlarm#172]
[ENHANCEMENT]
## Enhancement Description
Currently, the address of the pokemon alert is returning the default "browser" language.

## Use cases
Just add an argument on alarms/utils.py line 294:
result = config['GMAPS_CLIENT'].reverse_geocode((lat,lng), **language='zh-TW'**)[0]
language code is as follows:
https://developers.google.com/maps/faq?#languagesupport

**Comment by nhumber** [comment]
this does not work with tweets, i think twitter shortens the URL with t.co by default, can anyone think of a work around?

**Comment by kvangent** [comment]
@nhumber What do you mean it doesn't work? Like it is too long? Or you are getting errors?

**Comment by nhumber** [comment]
In Twitter currently you get a link with the preview image for google maps. when you click it, the web browser opens not google maps, then you have to click again and select open with google maps, and THEN there is no default location set so you need to select "From"and choose "Your location", before you can get acutual gps navigation.

While the notifications work perfectly, the end result be it because of twitter or something else is rather cumbersome, this is what happens on android, havent tested ios

Better result would be, get tweet, click link, google maps opens, hit "Navigate" and your off to said location.

is it possible to make the URL open in Google maps and not your browser first?

is it possible to include something in the URL which will default "Your Location" as the start point?

is the t.co shortened URL loosing some of this data?

**Comment by kvangent** [comment]
@nhumber I don't know, but if you open a new issue with the title  `[BUG] Twitter Gmaps Links not directing to google maps` I'll look into if there is anything we can do
