### ISSUE TITLE
[ENHANCEMENT] Add Pokémon IV-based notifications, from PR that will be pushed to main branch "soon".

### ISSUE THREAD

**Issue by Imoq** [kvangent/PokeAlarm#216]
## Enhancement Description

A big thread regarding adding IVs to a list of Pokémon is under discussion (https://github.com/PokemonGoMap/PokemonGo-Map/pull/1187) and one of the developers has said they will prioritize the PR. Somebody in the thread already modified PokeAlarm to alert you of some specific Pokémon IVs, it would be nice to have it for everybody once it goes out.

## Use cases

Have the IVs of the Pokémon you are interested in listed to decide if you want to go after them or not.

## Other Links

Link provided above.
Example of PokeAlarm already modified here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1187#issuecomment-246077200
Comment from developer about merging this soon here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1187#issuecomment-246078842

**Comment by azd2** [comment]
I did some adjustments to fit my personal needs. 
Since i have absolutely no idea of python, coding, git, etc., i won't create a pull request for this.
But if any of the real devs here think, that they can use some of the ideas while correcting what i may have done wrong: feel free to do so, here's the fork: https://github.com/azd2/PokeAlarm. I'd love to see this go in. 
As addition perhaps the individual Webhook msgs for IV, moves etc. should perhaps be made configurable regarding the fact that noone knows, which (if any) pull request scanning IVs will make into Pokemap at the end...

**Comment by lota7** [comment]
The pull from Mango is more likely to get added to main branch
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1239

**Comment by KongGal** [comment]
How would it fit together with twitters message length limit?

**Comment by nhumber** [comment]
it fits fine, Im using , '<name> (<iv>IV) (<move1>/move2> Till <12hr_time> (<time_left>) <gmaps>`
or something along those lines and i have no issues with everything getting sent

**Comment by lota7** [comment]
Could we get extented features done?
For example I would like to have notifications on every snorlax, lapras, dragonite that appears, and also on dratinis but ONLY if dratini is above 90%.

For example input in alarms.json
"Dratini":"10000, 90", (indicating notify of 10000 meter range, and IV of 90+)

**Comment by Spiritvn** [comment]
Already did @lota7 https://github.com/kvangent/PokeAlarm/pull/220

**Comment by jnovack** [comment]
IVs are causing major issues with bans for scanners.  I highly doubt it will be pushed "soon".  Lots of negative feedback in the Discord.

Also, can you give me 3 examples of Pokemon where you will WOULD go for a 100% but NOT a 0%?

In my mind, you are either getting up to get that pokemon or not.  A 0% Lapras is better than No Lapras.

**Comment by azd2** [comment]
@jnovack Many problems with bans? I started with the IV PR about 2 weeks ago. Out of 2000 accounts i used in the csvs (600 active over 61 Beehives, others for cycling if an acc is banned) 2 are banned. Thats around 0.1%. Perhaps if i would not have used the IV PRs those 2 accounts would not have been banned. But seriously...2 out of 2000? I had FAR more accounts banned before i used the IV PR when i used ss scanning without the speed limit PR. I believe limiting speed and using 1 Account per proxy has far more to do with avoiding bans than the IV PR has.
Regarding examples: Dragonite, Snorlax, Lapras, MrMime, Vaporeon, Flareon, Jolteon, Charizard, Venusaur, Pikachu, Raichu...the list is far longer. I have 45 Snorlax on my main account, only 1 has 100%IV. Why should i go for the 45th non 100% snorlax? Same goes for all other Pokemon... If i could not scan IVs the map would be of no use to me.
Please explain to me why a 0% Lapras is worth more than no Lapras after i threw away about 50 of them because they had bad IVs?
When my map would find a 100% lapras though i would go for it instantly.

**Comment by jnovack** [comment]
> Please explain to me why a 0% Lapras is worth more than no Lapras after i threw away about 50 of them because they had bad IVs?

1) 4 Candy if you transfer.
2) You won't take a 0% Level 30 (CP 2231) over a 100% Level 1 (CP 42) Lapras?  You can't get CP from the scanner unless you have Level 30 Scanners.

I wouldn't throw away the 42 Lapras, I would keep him as my buddy since I can get candy from him and won't put him in a gym.

**Comment by azd2** [comment]
Why in hell should i care if have 999 lapras candy or 1003 lapras candy? They are totally useless since they cannot evolve and i only need about 300 for levelling up the 100IV Lapras i still need to find in the area i scan ( i have one, but that's sniped from around half the world 3 months ago).
For me it's just not worth the effort to log in for catching annother 99 or less iv Lapras, Snorlax, Slowbro or whatever. I log in if Telegram notifies me of a 100 IV pokemon, and only if it's one i still search (i.e. not evee, pidgey, weedle etc.)
Your argumentation in 2 lacks a bit. How would you know that the 0 IV Pokemon has lvl 30 and log in to catch it? 
And yes... i would try to catch the 100 iv lvl 1 Pokemon. Even if next to it i found a lvl 30 0-99 iv lapras i would only catch that for the stardust/XP, but for sure i'd prefer it to be a weedle, pidgey or caterpie.
As long as one still needs to fill his pokedex it makes sense to go for some pokemon without knowing their IV. 
But if you have catched 100s of the rarest pokemon neither the map nor pokenotifier makes any sense if you cannot filter by IV.

**Comment by kvangent** [comment]
@jnovack @azd2 Some people care about IV's and some don't. IV/Moveset filtering is going to be added in because enough people want it. If you don't want it, don't use it.

**Comment by kvangent** [comment]
This is now added.
