### ISSUE TITLE
Pokemon dont trigger every now and then, running 2 instances

### ISSUE THREAD

**Issue by darkelement1987** [kvangent/PokeAlarm#225]
Right now im using 2 instances of pokealarms for 2 Telegram bots.

1 for normal Pokémon with it's own blacklist
1 for only the best pokemon with it's own blacklist.

Is it possible to merge the two of these into 1 instance of pokealarms because right now every now and then some pokemon's don't trigger to my 'normal'.

For example, today a Snorlax, Jolteon and Dragonair spawned and my 'normal' pokealarms instance didn't show them while the other instance did. It only happens occasionaly.

**Comment by reme-dy** [comment]
@darkelement1987 please complete the issue template.

**Comment by Talhoo** [comment]
I've been noticing it also.  the pokemon is on my map. But it didn't trigger. Is it possible it has been happening since this commit ?

https://github.com/kvangent/PokeAlarm/commit/8e4766d186a26b13d16af6b8f45a1a7ac696483a

I was gonna try and debug it, but I didn't want to commit the time into it if the new update 0.37 disabled maps. Since it's really hard to catch one. It doesn't happen a lot. And I have to just stare at my map and my slack to see when it happens.

**Comment by reme-dy** [comment]
What was your pokemongo-map command? have you been receiving empty upserts during scan?  Without the information we ask for in the template, it's difficult to chase down the problem.

**Comment by Talhoo** [comment]
I'll guess i'll follow up on this.

There's nothing special to my commands. Most of the stuff I've put in config anyway. I don't use -msl.
I'll see if tomorrow if I can get some debug logging going and catch one that doesn't trigger. It very rare happens

```
Start "Server Aalst" Python runserver.py -ss spawns.json -os -fl
Start "Workers Aalst" Python runserver.py -ns -j -ss spawns.json -ps -wh http://127.0.0.1:4000 
start "webhook" python runwebhook.py -c alarms.json
start "webhook2" python runwebhook.py -P 4001 -c alarms2.json
start "webhook3" python runwebhook.py -P 4002 -c alarms3.json
```
