### ISSUE TITLE
Not all webhooks are captured on PokeAlarm

### ISSUE THREAD

**Issue by derycklong** [kvangent/PokeAlarm#257]
Not all webhooks are captured on PokeAlarm.

I have checked on pogom db and the pokemon is registered in the db but Pokealarm failed to capture the pokemon.

**Comment by kvangent** [comment]
@derycklong Please use the issue template. Issues without it are always closed.

You said that you checked the database, but that doesn't confirm that PokemonGo-Map sent a webhook. It could also be that PokeAlarm caught the webhook and didn't alert you because of your setup. It's impossible to tell without more information.
