### ISSUE TITLE
[BUG] Is PokeAlarm compatible with Pokemon Go Desktop Map 0.4.1?

### ISSUE THREAD

**Issue by sterlingrpi** [kvangent/PokeAlarm#269]
## Problem Description
PokeAlarm initializes and I see it post the default message to Tweeter "Pokealarm has initialized! We will tweet..." however, on the command prompt window it does not show any pokemon and it does not tweet any pokemon specified in alarms.json.

I previously used PokeAlarm with Pokemon Go Desktop Map 0.3.4 with no problems. I reinstalled the requirements. And restarted both applications

## Your Environment
Operating System:  Windows 7
Python Version: 2.7  
PokemonGo-Map startup command: Desktop
PokeAlarm startup command: python runwebhook.py

Did the issue persist after restarting the script?: yes

## Console Output
No output other than initialization.

## Your Alarms Config
No changes.

## Troubleshooting Checklist
[X ] Most recent version of PokemonGo-Map
[X ] Most recent version of PokeAlarm
[X ] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
If you aren't seeing anything in the console window, that means PokeAlarm isn't receiving hits. This could be caused by:
1. Pokemon Go Desktop Map is not sending webhooks 
2. Is not sending webhooks to the right place
3. Something is blocking the webhooks before it gets to PokeAlarm

It's almost impossible to say without more information regarding your setup. Make sure that you have your webhook turned on and configured to the port PokeAlarm is listening on.

**Comment by sterlingrpi** [comment]
I managed to fix my problem. Basically just following the instructions I  went to my pokemon go desktop map instillation folder, copied config.ini.example to config.ini, and then the line added "webhook:http://127.0.0.1:4000"

It is strange I did not have to do this with earlier versions of desktop map. Guess they disabled webhooks by default? Either way, thank you for your help and excellent app!!!
