### ISSUE TITLE
Fix for pokemons not being pushed and request

### ISSUE THREAD

**Issue by vervsdvgwegfeg** [kvangent/PokeAlarm#3]
When I ran webhook it found a lot of pokemons but none were pushed to Pushbullet. Then I saw this: "2016-07-29 16:41:56,415 [ alarm_manager] [   INFO] Electabuzz notification was not triggered because time_left had passed."

In alarms\alarm_manager.py line 55 I changed 
from this:      elif dissapear_time < datetime.utcnow() :
to this:           elif dissapear_time > datetime.utcnow() :
because dissapear time must be larger than datetime.

![untitled](https://cloud.githubusercontent.com/assets/20638796/17252967/0281a350-55af-11e6-8873-c65aa77cb138.png)

It works now and notifications work. I just have this problem of notifications being pushed 1h in advance. Can you program it so all pushed pokemons have dissapear_time under 15 min (so it won't show that 45 min dissapear time). I as a novice would do someting like this:
(dissapear_time - datetime.utcnow() ) < 15min

But then again I am a complete amateur and don't know how you pros code...

**Comment by kvangent** [comment]
If dissapear_time is smaller, that means that that time has already passed. So the code should have been correct the way it was.

There are 15, 30 and 45 minute spawn times from my understanding.

There might be an issue with timezones causing issues with this. Can you send me some of the time you have been getting?

**Comment by vervsdvgwegfeg** [comment]
Sure. I am UTC +1:00
And here is my pushbullet chat:
![untitled](https://cloud.githubusercontent.com/assets/20638796/17254130/c4350e84-55b3-11e6-86e7-5a79deeb58a9.jpg)
Before the change (< into >) it didn't push notifications and now it does. I asked for help of 45min timers because I thought it was a phantom spawn just because it didn't show on the localhost:5000 MAP that pokemon so I thought it was an error...

**Comment by kvangent** [comment]
@vervsdvgwegfeg Please let me know if this fixes your issue.

For people having issues with time, the problem is that the PokemonGo-Map is sending a local object instead of a UTC one. I've submitted a [pull request](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2633), so hopefully they fix it soon.

If you want to fix it yourself, you just need to change two lines. Find the PokemonGo-Map/pgom/models.py and change the following lines:

Add `import calendar` to the list of imports.
Change line 269-270 to `'disappear_time': calendar.timegm(d_t.timetuple())` instead of `'disappear_time': time.mktime(d_t.timetuple())`.

This should fix your problem.
