### ISSUE TITLE
[ENHANCEMENT] CP Text Substitution 

### ISSUE THREAD

**Issue by PokeGymFighter** [kvangent/PokeAlarm#366]
## Enhancement Description
Have a text substitution field for CP - yes I know this has been raised before and closed however the CP is the same for everyone over level 30, so it would be a useful feature.

## Use cases
99% of people I know are all over Level 30, so it would be useful to know if that high IV Snorlax was 2700CP or 42CP before getting out of bed at 4am...

**Comment by kvangent** [comment]
>  yes I know this has been raised before and closed however the CP is the same for everyone over level 30, so it would be a useful feature.

The reason the issue has been closed isn't because I don't think it will be useful. It is because there is literally nothing I can do about it. RocketMap does  not send CP. I cannot magically make it do that. I can not magically calculate the information from what RocketMap sends. 

If you have another map that does send CP, and you want that map to be supported, you can open up a ticket for that and I will be able to make a custom webhook for it.
