### ISSUE TITLE
Change utc time to local

### ISSUE THREAD

**Issue by RicardoGA** [kvangent/PokeAlarm#4]
hi to ask if it's possible to change the disappear time from  utc to local time in the message "available until" ?? (im using slack)

**Comment by kvangent** [comment]
For people having issues with time, the problem is that the PokemonGo-Map is sending a local object instead of a UTC one. I've submitted a [pull request](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2633), so hopefully they fix it soon.

If you want to fix it yourself, you just need to change two lines. Find the PokemonGo-Map/pgom/models.py and change the following lines:

Add `import calendar` to the list of imports.
Change line 269-270 to `'disappear_time': calendar.timegm(d_t.timetuple())` instead of `'disappear_time': time.mktime(d_t.timetuple())`.

This should fix your problem.
