### ISSUE TITLE
Slack Icons issue

### ISSUE THREAD

**Issue by SkOODaT** [kvangent/PokeAlarm#54]
icons arent working for slack after recent changes

**Comment by reactortrip** [comment]
The repository he is calling is gone, needs to be changed to something else.

**Comment by Malouff** [comment]
You should use this project to mass upload emoji icons to slack
https://github.com/lambtron/emojipacks
and use this https://raw.githubusercontent.com/jaylynch/pokemoji/master/pokemon-by-name.yaml for the resource to upload

In the Message we could then do something like A wild :<pkmn> <pkmn> has appeared! to see the Image and Name.

Can you also edit you example to do it like the default message and show how to implement <dist>	*Distance from set location in meters

I also think that it would be nice if we could somehow edit alarms.json on the fly instead of starting and stopping the server.

**Comment by kvangent** [comment]
@Malouff To do distance you just use <dist> in one of the customizable fields for your alarm.

**Comment by kvangent** [comment]
@blaulan Would you be willing to do a more permanent method for these slack icons in a PR?

**Comment by fatmagic** [comment]
RE: Current Slack Icon Issue - It was calling the "master" branch, I went into the "slack_alarm.py" (line 38) and changed it to "/develop/" -- _e.g. icon_url='https://raw.githubusercontent.com/PokemonGoMap/PokemonGo-Map/**develop**/static/icons/{id}.png'.format(**pkinfo)_

**Comment by SkOODaT** [comment]
icon_url='https://raw.githubusercontent.com/PokemonGoMap/PokemonGo-Map/develop/static/icons/{id}.png'.format(**pkinfo) 

can confirm this works i did same thing figured it out lol
